ALTER TABLE CursoInstructor
ADD CONSTRAINT FK_CURSO_INSTRUCTOR_CURSO_ID
	FOREIGN KEY (CursoId)
	REFERENCES Curso(CursoId);

ALTER TABLE CursoInstructor
ADD CONSTRAINT FK_CURSO_INSTRUCTOR_INSTRUCTOR_ID
	FOREIGN KEY (InstructorId)
	REFERENCES Instructor(InstructorId);